# Generated by Django 4.1.3 on 2022-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='real_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tik', models.CharField(max_length=10, null=True)),
                ('cell_1', models.FloatField()),
                ('cell_2', models.FloatField()),
                ('cell_3', models.FloatField()),
                ('cell_4', models.FloatField()),
                ('cell_5', models.FloatField()),
                ('cell_6', models.FloatField()),
                ('cell_7', models.FloatField()),
                ('cell_8', models.FloatField()),
                ('cell_9', models.FloatField()),
                ('cell_10', models.FloatField()),
            ],
        ),
    ]
