# Generated by Django 4.1.3 on 2022-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nasa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_capacity', models.FloatField()),
            ],
        ),
    ]
